### ISSUE TITLE
Bump up integration_tests/packages.yml versioning to ensure full package coverage

### ISSUE THREAD

**Issue by fivetran-avinash** [fivetran/dbt_fivetran_utils#128]
We have recently upped the latest version of our `dbt_salesforce` package to 1.0.0, which is outside the range [of the current `integration_tests/packages.yml`](https://github.com/fivetran/dbt_fivetran_utils/blob/releases/v0.4.latest/integration_tests/packages.yml) of our latest `dbt_fivetran_utils` release.   We will want to extend the range of all our `packages.yml` to account for this and bundle this in a future release. 

Example bump: 

> 
>   - package: fivetran/salesforce
>     version: [">=0.1.0", "<1.0.0"]

to 

> 
>   - package: fivetran/salesforce
>     version: [">=0.1.0", "<2.0.0"]
>

**Comment by fivetran-joemarkiewicz** [comment]
This has been addressed within PR #130
