### ISSUE TITLE
Changes to dispatch in dbt v0.20

### ISSUE THREAD

**Issue by jtcohen6** [fivetran/dbt_fivetran_utils#29]
Hi team! I wanted to give you a heads up about a change coming in dbt v0.20. Let me know if you have questions, I'm more than happy to help.

### Required code change

We've made a change to `adapter.dispatch`: Instead of passing a `_get_namespaces()` macro to the `packages` arg, you should pass the name of this package (as a string) to the `macro_namespace` arg, which is now the second positional argument.

In practice, this just looks like switching each macro like:
https://github.com/fivetran/dbt_fivetran_utils/blob/854b0f1d0b41d283fec7cdc486e8dfc86ddc14b5/macros/ceiling.sql#L1-L5

To:
```sql
{% macro ceiling(num) -%}

{{ adapter.dispatch('ceiling', 'fivetran_utils') (num) }}

{%- endmacro %} 
```

I hope this could be as simple as Find + Replace for `packages = fivetran_utils._get_utils_namespaces()` &rarr; `'fivetran_utils'`.

If you prefer more explicit syntax, you could specify keyword names for each argument. What's below is exactly the same as what's above:
```sql
{% macro ceiling(num) -%}

{{ adapter.dispatch(macro_name = 'ceiling', macro_namespace = 'fivetran_utils') (num) }}

{%- endmacro %} 
```

### For the README

If a user wishes to override/shim this package, instead of defining a var named `fivetran_utils_dispatch_list`, they should now define [a config](https://next.docs.getdbt.com/reference/project-configs/dispatch-config) in `dbt_project.yml`.

There's one crucial caveat: Your `_get_utils_namespaces` macro works just a little differently from everyone else's today. In order to maintain the current behavior of searching in `dbt_utils` _and then_ `fivetran_utils`, all users of Fivetran packages will need to specify at least this much:
```yml
dispatch:
  - macro_namespace: fivetran_utils
    search_order: ['dbt_utils', 'fivetran_utils']
```

They could add other packages to that list, too, for instance `spark_utils` or `<name_of_their_project>` (if they wish to override/reimplement certain macros).

One thought: It doesn't look like the `fivetran_utils` package currently requires `dbt_utils` in its `packages.yml` today. It really should, if you want to maintain the behavior of dispatching to `dbt_utils` before dispatching to `fivetran_utils`. If the `dbt_utils` package isn't installed, that will raise an error.

### Notes

This change is in dbt v0.19.2 as well. **Both v0.19.2 and v0.20.0 have backwards compatibility for the old syntax**, so there's no huge rush to upgrade. The old syntax will start raising a deprecation warning in v0.20. As soon as you do upgrade to the new syntax, you'll need to require `dbt >= 0.19.2` (or just `>=0.20.0`, for simplicity, since you're already making compatibility changes in #69).

See also:
- https://github.com/fishtown-analytics/dbt/issues/3383
- https://next.docs.getdbt.com/reference/dbt-jinja-functions/dispatch

**Comment by fivetran-joemarkiewicz** [comment]
Thanks so much for bringing this to our attention @jtcohen6!

The updates you mentioned do seem that they will be as easy as a find/replace and I agree with you that we should add dbt_utils to our packages.yml. Do you know if there are any other downsides to refraining from making these updates at the moment other than the depreciation warning? Also do you know when this backwards compatibility will in fact be depreciated?

**Comment by jtcohen6** [comment]
> Do you know if there are any other downsides to refraining from making these updates at the moment other than the depreciation warning?

I don't think so. I haven't explicitly tested interaction between packages that have upgraded to the new syntax and packages that are still using the old syntax, but my sense is that a user could have one of each installed, and they should both work.

> Also do you know when this backwards compatibility will in fact be depreciated?

Most likely, we'll remove this backwards compatibility and deprecate the old syntax when we release dbt v1.0.0 at the end of this year.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks again for your help on this update @jtcohen6. Closing this issue as the recent `v0.2.x` releases institute this update. 🕺
