### ISSUE TITLE
Update staging model automation macro

### ISSUE THREAD

**Issue by fivetran-reneeli** [fivetran/dbt_fivetran_utils#60]
- the readme needs to be updated with the 2 new sh files
- in [generate_models.sh](https://github.com/fivetran/dbt_fivetran_utils/blob/releases/v0.3.latest/generate_models.sh) currently it appends the sql to the staging model, change to replace

**Comment by fivetran-joemarkiewicz** [comment]
This has been merged into the latest `releases/v0.3.latest` branch.
