### ISSUE TITLE
Update master readme to link to latest release version

### ISSUE THREAD

**Issue by fivetran-catfritz** [fivetran/dbt_fivetran_utils#86]
When viewing the repo for [dbt_fivetran_utils](https://github.com/fivetran/dbt_fivetran_utils), the branch defaults to `master`, which is not the currently released branch. 

To prevent confusing anyone unfamiliar with the repo, we should add a disclaimer in the `master` README with a link or redirect to the latest release version since we should not change the default branch. See [example of a deprecated package](https://github.com/dbt-labs/quickbooks) from dbt-labs.

**Comment by fivetran-joemarkiewicz** [comment]
@fivetran-catfritz since that has been completed and merged into `master` we can close this issue out.
