### ISSUE TITLE
Feature - Adjust Union Relations to use sources or references

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_fivetran_utils#88]
**Are you a current Fivetran customer?**
Fivetran created PR

**Describe the bug**
Currently the `union_data` macro does not utilize sources when unioning the data. This can cause a number of issues, one in part being that it does not effectively test freshness (as stated in Issue #52); however, another issue is that within Fivetran Transformations for dbt Core this union feature will not effectively work since Fivetran expects a corresponding source when orchestrating transformations. Therefore, we will want to ensure the `union_data` macro can be built off a source reference.

However, if we do this, all previous implementations of the `union_data` macro will break. We will want to find a way for the `union_data` macro to leverage the current way **but also** leverage the sources if a users defines the sources. This is something I could see us wanting to fold into the `releases/v0.4.latest` version of Fivetran Utils.

**Additional Details**
I was able to get a working version implemented within PR #82. However, it has not been fully evaluated and would need to be reworked in order to be scalable and implemented properly without breaking all existing implementations of the macro.

**Comment by fivetran-jamie** [comment]
this work has been done right?

**Comment by fivetran-joemarkiewicz** [comment]
Correct, it has! Closing this out. PR #89 addresses this feature.
